name: ToDo App Workflow

# このワークフローは、リポジトリにプッシュされたときにトリガーされます
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
    
    # Docker Compose をインストール
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Azure Container Registry にログイン
    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
      
    - name: 'Build and push Docker image'
      env:
        COSMOS_DB_ENDPOINT: ${{ secrets.COSMOS_DB_ENDPOINT }}
        COSMOS_DB_KEY: ${{ secrets.COSMOS_DB_KEY }}
      run: |
        docker-compose -f docker-compose.prod.yml build \
          --build-arg COSMOS_DB_ENDPOINT=${COSMOS_DB_ENDPOINT} \
          --build-arg COSMOS_DB_KEY=${COSMOS_DB_KEY}
        docker tag todo-app:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/todo-app:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/todo-app:${{ github.sha }}

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: todo-app-${{ github.run_number }}
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/todo-app:${{ github.sha }}
        cpu: 1
        memory: 1
        environment-variables: COSMOS_DB_ENDPOINT=${{ secrets.COSMOS_DB_ENDPOINT }}
        secure-environment-variables: COSMOS_DB_KEY=${{ secrets.COSMOS_DB_KEY }}
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: todo-app
        location: 'japan east'
        ports: 443